categories: Kategorie
search: Szukaj
tags: Tagi
tagcloud: "Tag Cloud"
tweets: Tweety
prev: Poprzedni
next: Nastepny
comment: Komentarze
archive_a: Archiwum
archive_b: "Archiwum: %s"
page: "Strona %d"
recent_posts: "Aktualne wpisy"
description: Opis
read_more: "Czytaj wiecej"
links: Linki
about: O mnie
fanpage: Fanpage
about_text: Piotr Trocki
about_text_2: 
	"Pasjonat tańca towarzyskiego. 
	Z tańcem związany od 6 roku życia. 
	Na blogu prezentuję porady dla osób zaintesowanych tańcem oraz zdrowym trybem życia."
about_img: /blog/img/cutmypic.png