categories: Kategorie
search: Szukaj
tags: Tagi
tagcloud: "Tag Cloud"
tweets: Tweety
prev: Poprzedni
next: Nastepny
comment: Komentarze
archive_a: Archiwum
archive_b: "Archiwum: %s"
page: "Strona %d"
recent_posts: "Aktualne wpisy"
description: Opis
read_more: "Czytaj wiecej"
links: Linki
about: O mnie
fanpage: Fanpage
about_text: Piotr Badura
about_text_2: 
	"Na blogu prezentuję porady dla osób zaintesowanych tańcem oraz zdrowym trybem życia."