slogan: "Kochamtaniec"

menu:
  - title: Blog
    url: 
    intro: "Blog"
    icon: "fa fa-archive"
  - title: Kontakt
    url: contact
    intro: "Kontakt"
    icon: "fa fa-envelope"
  - title: O mnie
    url: about
    intro: "O mnie"
    icon: "fa fa-user"

links:
  - title: "Facebook"
    url: https://www.facebook.com/kochamtaniecpl
    intro: "Facebook"
    icon: "fa fa-facebook"
  - title: "Twitter"
    url: https://www.twitter.com/kochamtaniecpl
    intro: "twitter"
    icon: "fa fa-twitter"

widgets:
  - aboutme
  - category
  - tagcloud
  - recent_posts  
  - links

rss: 
fancybox: true
favicon: favicon.ico
duoshuo_shortname:

# Analytics
google_analytics:
  enable: true
  siteid: UA-66865654-1
