slogan: "Yet another bootstrap theme."

menu:
  - title: Blog
    url: 
    intro: "Blog"
    icon: "fa fa-archive"
  - title: Kontakt
    url: contact
    intro: "Kontakt"
    icon: "fa fa-tags"
  - title: O nas
    url: about
    intro: "O nas."
    icon: "fa fa-user"

links:
  - title: Freemind
    url: https://github.com/wzpan/freemind/
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/wzpan
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: http://www.linkedin.com/in/hahack
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
swiftype_key: ZP2ZSuHgipSZfRyU8uTR