slogan: "Yet another bootstrap theme."

menu:
  - title: Blog
    url: 
    intro: "Blog"
    icon: "fa fa-archive"
  - title: Kontakt
    url: contact
    intro: "Kontakt"
    icon: "fa fa-tags"
  - title: O nas
    url: about
    intro: "O nas."
    icon: "fa fa-user"

links:
  - title: "Facebook"
    url: https://www.facebook.com/kochamtaniecpl
    intro: "Facebook"
    icon: "fa fa-fb"
  - title: "Twitter"
    url: https://www.twitter.com/kochamtaniecpl
    intro: "twitter"
    icon: "fa fa-tw"

widgets:
- search
- category
- recent_posts  
- links
- tagcloud

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# Analytics
google_analytics:
  enable: true
  siteid:UA-66865654-1
baidu_tongji:
  enable: false
  siteid:

# search
swiftype_key: ZP2ZSuHgipSZfRyU8uTR